### PR TITLE
Bonjemus Synapse 2.8.1 update

### PR DESCRIPTION
**Pull request by Bonjemus**
Yes

### CODE REVIEW

**Comment by Bonjemus** [comment]
Don't look at the 7 commits, I had troubles with GitHub.

**Comment by Bonjemus** [comment]
OK I'm kind of stupid actually... :T

**Comment by GrafDimenzio** [comment]
The Changes are alright and could be applied but you added a bunch of other unnecessary files that should be removed before merging

**Comment by Bonjemus** [comment]
I deleted all the unnecesarry files.

**Pull request merged**
